<Entities>
  <!--

  ENTITY - the parts common to all entities.

  -->
  <Entity Name="Entity">
    <Field Name="IsInPaperSpace" Code="67" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" DisableWritingDefault="true" MinVersion="R12" />
    <Field Name="Layer" Code="8" Type="string" DefaultValue='"0"' WriteConverter='defaultIfEmpty(%v, "0")' />
    <Field Name="LineTypeName" Code="6" Type="string" DefaultValue='"BYLAYER"' DisableWritingDefault="true" />
    <Field Name="Elevation" Code="38" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" MaxVersion="R12" />
    <Field Name="MaterialHandle" Code="347" Type="string" DefaultValue='"BYLAYER"' DisableWritingDefault="true" MinVersion="R2007" />
    <Field Name="Color" Code="62" Type="Color" DefaultValue="ByLayer()" ReadConverter="Color(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="LineWeight" Code="370" Type="LineWeight" DefaultValue="NewLineWeightStandard()" ReadConverter="LineWeight(%v)" WriteConverter="int16(%v)" MinVersion="R2000" />
    <Field Name="LineTypeScale" Code="48" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" MinVersion="R13" />
    <Field Name="IsVisible" Code="60" Type="bool" DefaultValue="true" ReadConverter="!boolFromShort(%v)" WriteConverter="shortFromBool(!%v)" DisableWritingDefault="true" MinVersion="R13" />
    <Field Name="ImageByteCount" Code="92" Type="int" DefaultValue="0" DisableWritingDefault="true" MinVersion="R2000" />
    <Field Name="PreviewImageData" Code="310" Type="string" DefaultValue="[]string{}" AllowMultiples="true" MinVersion="R2000" />
    <Field Name="Color24Bit" Code="420" Type="int" DefaultValue="0" DisableWritingDefault="true" MinVersion="R2004" />
    <Field Name="ColorName" Code="430" Type="string" DefaultValue='""' MinVersion="R2004" />
    <Field Name="Transparency" Code="440" Type="int" DefaultValue="0" MinVersion="R2004" />
    <!-- <Pointer Name="PlotStyle" Code="390" Type="IDxfItem" MinVersion="R2007" /> -->
    <Field Name="ShadowMode" Code="284" Type="ShadowMode" DefaultValue="ShadowModeCastsAndReceivesShadows" ReadConverter="ShadowMode(%v)" WriteConverter="int16(%v)" MinVersion="R2007" />
    <WriteOrder>
      <!-- TODO: 5/handle -->
      <WriteExtensionData />
      <!-- TODO: 330/owner-handle -->
      <WriteSpecificValue Code="100" Value='"AcDbEntity"' />
      <WriteField Field="IsInPaperSpace" />
      <WriteField Field="Layer" />
      <WriteField Field="LineTypeName" />
      <WriteField Field="Elevation" />
      <WriteField Field="MaterialHandle" />
      <WriteField Field="Color" />
      <WriteField Field="LineWeight" />
      <WriteField Field="LineTypeScale" />
      <WriteField Field="IsVisible" />
      <WriteField Field="ImageByteCount" />
      <WriteField Field="PreviewImageData" />
      <WriteField Field="Color24Bit" />
      <WriteField Field="ColorName" />
      <WriteField Field="Transparency" />
      <!-- <WriteField Field="PlotStyle" /> -->
      <WriteField Field="ShadowMode" />
    </WriteOrder>
  </Entity>
  <!--

  3DFACE

  -->
  <Entity Name="Face" SubclassMarker="AcDbFace" TypeString="3DFACE">
    <Field Name="FirstCorner" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="SecondCorner" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="ThirdCorner" Code="12" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="12,22,32" />
    <Field Name="FourthCorner" Code="13" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="13,23,33" />
    <Field Name="EdgeFlags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true">
      <Flag Name="FirstEdgeInvisible" Mask="1" />
      <Flag Name="SecondEdgeInvisible" Mask="2" />
      <Flag Name="ThirdEdgeInvisible" Mask="4" />
      <Flag Name="FourthEdgeInvisible" Mask="8" />
    </Field>
  </Entity>
  <!--

  3DSOLID

  -->
  <Entity Name="Solid" SubclassMarker="AcDbModelerGeometry" TypeString="3DSOLID" MinVersion="R13">
    <Field Name="FormatVersionNumber" Code="70" Type="int16" DefaultValue="1" />
    <Field Name="CustomData" Code="1" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="CustomData2" Code="3" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <!-- <Pointer Name="HistoryObject" Code="350" Type="IDxfItem" MinVersion="R2007" /> -->
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbModelerGeometry"' />
      <WriteField Field="FormatVersionNumber" />
      <WriteField Field="CustomData" />
      <WriteField Field="CustomData2" />
      <WriteSpecificValue Code="100" Value='"AcDb3dSolid"' MinVersion="R2007" />
      <!-- <WriteField Field="HistoryObject" /> -->
    </WriteOrder>
  </Entity>
  <!--

  ACAD_PROXY_ENTITY

  -->
  <Entity Name="ProxyEntity" SubclassMarker="AcDbProxyEntity" TypeString="ACAD_PROXY_ENTITY" MinVersion="R14" GenerateReader="false">
    <Field Name="readingGraphicsData" Type="bool" DefaultValue="true" />
    <Field Name="ProxyEntityClassId" Code="90" Type="int" DefaultValue="498" />
    <Field Name="ApplicationEntityClassId" Code="91" Type="int" DefaultValue="500" />
    <Field Name="GraphicsData" Type="[]byte" DefaultValue="[]byte{}" />
    <Field Name="graphicsDataSize" Code="92" Type="int" DefaultValue="0" />
    <Field Name="graphicsDataString" Code="310" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="EntityData" Type="[]byte" DefaultValue="[]byte{}" />
    <Field Name="entityDataSize" Code="93" Type="int" DefaultValue="0" />
    <Field Name="entityDataString" Code="310" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="ObjectID1" Code="330" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="ObjectID2" Code="340" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="ObjectID3" Code="350" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="ObjectID4" Code="360" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="Terminator" Code="94" Type="int" DefaultValue="0" />
    <Field Name="objectDrawingFormat" Code="95" Type="uint" DefaultValue="0" ReadConverter="uint(%v)" WriteConverter="int(%v)" MinVersion="R2000" />
    <Field Name="OriginalDataFormatIsDxf" Code="70" Type="bool" DefaultValue="true" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2000" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbProxyEntity"' />
      <WriteField Field="ProxyEntityClassId" />
      <WriteField Field="ApplicationEntityClassId" />
      <WriteSpecificValue Code="92" Value="len(this.GraphicsData)" />
      <WriteField Field="graphicsDataString" />
      <WriteSpecificValue Code="93" Value="len(this.EntityData)" />
      <WriteField Field="entityDataString" />
      <WriteField Field="ObjectID1" />
      <WriteField Field="ObjectID2" />
      <WriteField Field="ObjectID3" />
      <WriteField Field="ObjectID4" />
      <WriteField Field="Terminator" />
      <WriteField Field="objectDrawingFormat" />
      <WriteField Field="OriginalDataFormatIsDxf" />
    </WriteOrder>
  </Entity>
  <!--

  ARC

  -->
  <Entity Name="Arc" SubclassMarker="AcDbArc" TypeString="ARC">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Center" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Radius" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="StartAngle" Code="50" Type="float64" DefaultValue="0.0" Comment="Arc start angle in degrees" />
    <Field Name="EndAngle" Code="51" Type="float64" DefaultValue="360.0" Comment="Arc end angle in degrees" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbCircle"' />
      <WriteField Field="Thickness" />
      <WriteField Field="Center" />
      <WriteField Field="Radius" />
      <WriteField Field="Normal" />
      <WriteSpecificValue Code="100" Value='"AcDbArc"' />
      <WriteField Field="StartAngle" />
      <WriteField Field="EndAngle" />
    </WriteOrder>
  </Entity>
  <!--

  ARCALIGNEDTEXT

  -->
  <Entity Name="ArcAlignedText" SubclassMarker="AcDbArcAlignedText" TypeString="ARCALIGNEDTEXT" MinVersion="R2000" MaxVersion="R2000">
    <Field Name="Text" Code="1" Type="string" DefaultValue='""' />
    <Field Name="FontName" Code="2" Type="string" DefaultValue='""' />
    <Field Name="BigfontName" Code="3" Type="string" DefaultValue='""' />
    <Field Name="TextStyleName" Code="7" Type="string" DefaultValue='""' />
    <Field Name="CenterPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="ArcRadius" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="WidthFactor" Code="41" Type="float64" DefaultValue="1.0" />
    <Field Name="TextHeight" Code="42" Type="float64" DefaultValue="0.0" />
    <Field Name="CharacterSpacing" Code="43" Type="float64" DefaultValue="0.0" />
    <Field Name="OffsetFromArc" Code="44" Type="float64" DefaultValue="0.0" />
    <Field Name="RightOffset" Code="45" Type="float64" DefaultValue="0.0" />
    <Field Name="LeftOffset" Code="46" Type="float64" DefaultValue="0.0" />
    <Field Name="StartAngle" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="EndAngle" Code="51" Type="float64" DefaultValue="0.0" />
    <Field Name="IsCharacterOrderReversed" Code="70" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="DirectionFlag" Code="71" Type="int16" DefaultValue="0" />
    <Field Name="AlignmentFlag" Code="72" Type="int16" DefaultValue="0" />
    <Field Name="SideFlag" Code="73" Type="int16" DefaultValue="0" />
    <Field Name="IsBold" Code="74" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="IsItalic" Code="75" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="IsUnderline" Code="76" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="CharacterSetValue" Code="77" Type="int16" DefaultValue="0" />
    <Field Name="PitchAndFamilyValue" Code="78" Type="int16" DefaultValue="0" />
    <Field Name="FontType" Code="79" Type="FontType" DefaultValue="FontTypeTTF" ReadConverter="FontType(%v)" WriteConverter="int16(%v)" />
    <Field Name="ColorIndex" Code="90" Type="int" DefaultValue="0" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="WizardFlag" Code="280" Type="int16" DefaultValue="0" />
  </Entity>
  <!--

  ATTDEF

  -->
  <Entity Name="AttributeDefinition" SubclassMarker="nil" TypeString="ATTDEF" GenerateReader="false">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="TextHeight" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="Value" Code="1" Type="string" DefaultValue='""' />
    <Field Name="Rotation" Code="50" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="RelativeXScaleFactor" Code="41" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="ObliqueAngle" Code="51" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="TextStyleName" Code="7" Type="string" DefaultValue='"STANDARD"' DisableWritingDefault="true" />
    <Field Name="TextGenerationFlags" Code="71" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true">
      <Flag Name="IsTextBackward" Mask="2" />
      <Flag Name="IsTextUpsideDown" Mask="4" />
    </Field>
    <Field Name="HorizontalTextJustification" Code="72" Type="HorizontalTextJustification" DefaultValue="HorizontalTextJustificationLeft" ReadConverter="HorizontalTextJustification(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="SecondAlignmentPoint" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="Version" Code="280" Type="Version" DefaultValue="VersionR2010" ReadConverter="Version(%v)" WriteConverter="int16(%v)" MinVersion="R2010" />
    <Field Name="Prompt" Code="3" Type="string" DefaultValue='""' />
    <Field Name="TextTag" Code="2" Type="string" DefaultValue='""' />
    <Field Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="IsInvisible" Mask="1" />
      <Flag Name="IsConstant" Mask="2" />
      <Flag Name="IsInputVerificationRequired" Mask="4" />
      <Flag Name="IsAttributePresent" Mask="8" />
    </Field>
    <Field Name="FieldLength" Code="73" Type="int16" DefaultValue="0" DisableWritingDefault="true" />
    <Field Name="VerticalTextJustification" Code="74" Type="VerticalTextJustification" DefaultValue="VerticalTextJustificationBaseline" ReadConverter="VerticalTextJustification(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" MinVersion="R12" />
    <Field Name="IsLockedInBlock" Code="280" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="KeepDuplicateRecords" Code="280" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="MTextFlag" Code="70" Type="MTextFlag" DefaultValue="MTextFlagMultilineAttribute" ReadConverter="MTextFlag(%v)" WriteConverter="int16(%v)" MinVersion="R2007" />
    <Field Name="IsReallyLocked" Code="70" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="secondaryAttributeHandlesCount" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" MinVersion="R2007" />
    <Field Name="SecondaryAttributeHandles" Code="340" Type="string" DefaultValue="[]string{}" AllowMultiples="true" MinVersion="R2007" />
    <Field Name="AlignmentPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" MinVersion="R2007" />
    <Field Name="AnnotationScale" Code="40" Type="float64" DefaultValue="1.0" MinVersion="R2007" />
    <Field Name="XRecordTag" Code="2" Type="string" DefaultValue='""' MinVersion="R2007" />
    <!-- entity has a trailing MText -->
    <Field Name="MText" Code="-1" Type="MText" DefaultValue="*NewMText()" />
    <!-- private tracking fields -->
    <Field Name="lastSubclassMarker" Code="-1" Type="string" DefaultValue='""' />
    <Field Name="isVersionSet" Code="-1" Type="bool" DefaultValue="false" />
    <Field Name="xrecCode70Count" Code="-1" Type="int" DefaultValue="0" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbText"' MinVersion="R13" />
      <WriteField Field="Thickness" />
      <WriteField Field="Location" />
      <WriteField Field="TextHeight" />
      <WriteField Field="Value" />
      <WriteSpecificValue Code="100" Value='"AcDbAttributeDefinition"' MinVersion="R13" />
      <WriteField Field="Rotation" />
      <WriteField Field="RelativeXScaleFactor" />
      <WriteField Field="ObliqueAngle" />
      <WriteField Field="TextStyleName" />
      <WriteField Field="TextGenerationFlags" />
      <WriteField Field="HorizontalTextJustification" />
      <WriteField Field="SecondAlignmentPoint" />
      <WriteField Field="Normal" />
      <WriteSpecificValue Code="100" Value='"AcDbAttributeDefinition"' MinVersion="R13" />
      <WriteField Field="Version" />
      <WriteField Field="Prompt" />
      <WriteField Field="TextTag" />
      <WriteField Field="Flags" />
      <WriteField Field="FieldLength" />
      <WriteField Field="VerticalTextJustification" />
      <WriteField Field="IsLockedInBlock" />
      <WriteSpecificValue Code="100" Value='"AcDbXrecord"' MinVersion="R2007" />
      <WriteField Field="KeepDuplicateRecords" />
      <WriteField Field="MTextFlag" />
      <WriteField Field="IsReallyLocked" />
      <WriteSpecificValue Code="70" Value="int16(len(this.SecondaryAttributeHandles))" MinVersion="R2007" />
      <WriteField Field="SecondaryAttributeHandles" />
      <WriteField Field="AlignmentPoint" />
      <WriteField Field="AnnotationScale" />
      <WriteField Field="XRecordTag" />
    </WriteOrder>
  </Entity>
  <!--

  CIRCLE

  -->
  <Entity Name="Circle" SubclassMarker="AcDbCircle" TypeString="CIRCLE">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Center" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Radius" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbCircle"' />
      <WriteField Field="Thickness" />
      <WriteField Field="Center" />
      <WriteField Field="Radius" />
      <WriteField Field="Normal" />
    </WriteOrder>
  </Entity>
  <!--

  LINE

  -->
  <Entity Name="Line" SubclassMarker="AcDbLine" TypeString="LINE,3DLINE">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="P1" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="P2" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--

  MTEXT

  -->
  <Entity Name="MText" SubclassMarker="AcDbMText" TypeString="MTEXT" MinVersion="R13" GenerateReader="false">
    <Field Name="InsertionPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="InitialTextHeight" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="ReferenceRectangleWidth" Code="41" Type="float64" DefaultValue="1.0" />
    <Field Name="AttachmentPoint" Code="71" Type="AttachmentPoint" DefaultValue="AttachmentPointTopLeft" ReadConverter="AttachmentPoint(%v)" WriteConverter="int16(%v)" />
    <Field Name="DrawingDirection" Code="72" Type="DrawingDirection" DefaultValue="DrawingDirectionLeftToRight" ReadConverter="DrawingDirection(%v)" WriteConverter="int16(%v)" />
    <Field Name="ExtendedText" Code="3" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="Text" Code="1" Type="string" DefaultValue='""' />
    <Field Name="TextStyleName" Code="7" Type="string" DefaultValue='"STANDARD"' DisableWritingDefault="true" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="XAxisDirection" Code="11" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="11,21,31" />
    <Field Name="HorizontalWidth" Code="42" Type="float64" DefaultValue="1.0" />
    <Field Name="VerticalHeight" Code="43" Type="float64" DefaultValue="1.0" />
    <Field Name="RotationAngle" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="LineSpacingStyle" Code="73" Type="MTextLineSpacingStyle" DefaultValue="MTextLineSpacingStyleAtLeast" ReadConverter="MTextLineSpacingStyle(%v)" WriteConverter="int16(%v)" />
    <Field Name="LineSpacingFactor" Code="44" Type="float64" DefaultValue="1.0" />
    <Field Name="BackgroundFillSetting" Code="90" Type="BackgroundFillSetting" DefaultValue="BackgroundFillSettingOff" ReadConverter="BackgroundFillSetting(%v)" WriteConverter="int(%v)" />
    <Field Name="BackgroundColorRGB" Code="420" Type="int" DefaultValue="0" />
    <Field Name="BackgroundColorName" Code="430" Type="string" DefaultValue='""' />
    <Field Name="FillBoxScale" Code="45" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="BackgroundFillColor" Code="63" Type="Color" DefaultValue="ByLayer()" ReadConverter="Color(%v)" WriteConverter="int16(%v)" />
    <Field Name="BackgroundFillColorTransparency" Code="441" Type="int" DefaultValue="0" />
    <Field Name="ColumnType" Code="75" Type="int16" DefaultValue="0" />
    <Field Name="columnCount" Code="76" Type="int16" DefaultValue="0" WriteConverter="int16(%v)" />
    <Field Name="IsColumnFlowReversed" Code="78" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="IsColumnAutoHeight" Code="79" Type="bool" DefaultValue="true" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="ColumnWidth" Code="48" Type="float64" DefaultValue="0.0" />
    <Field Name="ColumnGutter" Code="49" Type="float64" DefaultValue="0.0" />
    <Field Name="ColumnHeights" Code="50" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <!-- private tracking fields -->
    <Field Name="readingColumnData" Code="-1" Type="bool" DefaultValue="false" />
    <Field Name="readColumnCount" Code="-1" Type="bool" DefaultValue="false" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbMText"' />
      <WriteField Field="InsertionPoint" />
      <WriteField Field="InitialTextHeight" />
      <WriteField Field="ReferenceRectangleWidth" />
      <WriteField Field="AttachmentPoint" />
      <WriteField Field="DrawingDirection" />
      <WriteField Field="ExtendedText" />
      <WriteField Field="Text" />
      <WriteField Field="TextStyleName" />
      <WriteField Field="ExtrusionDirection" />
      <WriteField Field="XAxisDirection" />
      <WriteField Field="HorizontalWidth" />
      <WriteField Field="VerticalHeight" />
      <WriteField Field="RotationAngle" />
      <WriteField Field="LineSpacingStyle" />
      <WriteField Field="LineSpacingFactor" />
      <WriteField Field="BackgroundFillSetting" />
      <WriteField Field="BackgroundColorRGB" />
      <WriteField Field="BackgroundColorName" />
      <WriteField Field="FillBoxScale" />
      <WriteField Field="BackgroundFillColor" />
      <WriteField Field="BackgroundFillColorTransparency" />
      <WriteField Field="ColumnType" />
      <WriteField Field="columnCount" />
      <WriteField Field="IsColumnFlowReversed" />
      <WriteField Field="IsColumnAutoHeight" />
      <WriteField Field="ColumnWidth" />
      <WriteField Field="ColumnGutter" />
      <WriteSpecificValue Code="50" Value="float64(len(this.ColumnHeights))" />
      <WriteField Field="ColumnHeights" />
    </WriteOrder>
  </Entity>
</Entities>
